### ISSUE TITLE
statnet.org contact email address does not work

### ISSUE THREAD

**Issue by mr-c** [statnet/Workshops#12]
statnet.org redirects to https://github.com/statnet/Workshops/wiki which instructs the reader to use statnet_help@u.washington.edu but that emailing that address results in

> You are not allowed to post to this mailing list, and your message has
been automatically rejected.  If you think that your messages are
being rejected in error, contact the mailing list owner at
statnet_help-owner@mailman13.u.washington.edu.

**Comment by krivit** [comment]
Whom are you trying to contact? Each package has a maintainer e-mail address, and only one of them (`latentnet`) is currently an `@statnet.org` address.

`statnet_help@u.washington.edu` is a public mailing list for getting help on using Statnet packages.

**Comment by mr-c** [comment]
@krivit My main issue is at https://github.com/statnet/statnet.common/issues/7 but I wanted to bring attention to email address issue as well.

**Comment by krivit** [comment]
@CarterButts , do we have a catch-all address on `statnet.org`?

**Comment by martinamorris** [comment]
We have a new email address for statnet:  contact@statnet.org

I will update the various online/workshop materials to reflect this, and close when I've completed.

**Comment by martinamorris** [comment]
new contact email has been added to:

* statnet.org landing page
* github.com/statnet organization landing page
* Workshop wiki page mailto
* chunk included front matter for all statnet workshops

**Comment by mr-c** [comment]
@martinamorris Thanks! I also updated the contact information within Debian for the next time we release an updated package.
