### ISSUE TITLE
session.Info() not updating in ergm tutorial

### ISSUE THREAD

**Issue by martinamorris** [statnet/Workshops#3]
i'm getting some odd behavior from the session.info() command at the top of the ergm tutorial.  it's executed as a simple r code chunk in the tutorial:

```{r}
sessionInfo()
```

and i've updated to R 3.6 on my laptop (verified when i run session.Info() from the command line.

but the output shown in Rstudio's  "R notebook" format (i.e., as i'm editing the  ergm_tutorial.Rmd file) shows R 3.5.1, and the knitted tutorial shows R 3.4.1:

![image](https://user-images.githubusercontent.com/8194530/59160218-7daa2a00-8a88-11e9-9aba-409f6f5b91c8.png)

googled but can't find anything relevant.  though weirdly, [this site](https://holtzy.github.io/Pimp-my-rmd/) is also showing 3.4.1 as the output of a call to session.Info.

i've pushed my commits to the tutorial.  can someone else pls. test and see what they get?

**Comment by drh20drh20** [comment]
I just compiled the whole .Rmd file in RStudio on my mac with no problems.  In particular, the "sessionInfo()" command seems to be working just fine and it gives me R 3.6.0.
I agree it's bizarre that you're getting different behavior from sessionInfo() depending on whether you call it directly at the console window vs. within an .Rmd file.  Did you actually re-knit the .Rmd in RStudio?  (If not, then this explains it.)
Also, I'm not sure why it's weird that the outside site would be showing 3.4.1; it seems this was the version in place at the time that person knitted the Rmd.

**Comment by martinamorris** [comment]
> Did you actually re-knit the .Rmd in RStudio?

indeed i did, which is why i found that so weird.  and i just thought it odd that the website i found while googling the error had the same exact 3.4.1 version showing.

in any case, i tested on another machine with a fresh install of everything, and it seems to be working fine.  it may be the cache call up top: 

`knitr::opts_chunk$set(cache=T, comment=NA)`

there seem to be some other problems with that laptop now -- of course just in time for Sunbelt.  so it's hard to say.  but i'll close this ticket, as things seem to be working on other machines.

**Comment by drh20drh20** [comment]
Ah--I think you're correct about the opts_chunk call.   I hadn't known about this.
You probably already found this but just in case:  https://yihui.name/knitr/options/#cache

**Comment by sgoodreau** [comment]
Yeah, just saw this thread now, but as soon as I saw the first email, I thought, "This is gonna be a cache issue".
