### ISSUE TITLE
Freeze a release of the workshops repository from the 2019 Sunbelt

### ISSUE THREAD

**Issue by sgoodreau** [statnet/Workshops#8]
I think we decided we wanted to do this after each iteration of workshops being presented publicly, for the historical record?

**Comment by martinamorris** [comment]
> I think we decided we wanted to do this after each iteration of workshops being presented publicly, for the historical
> record?

Yep, thx!

I'll chat with Sara about the best approach for this.  Apparently the 
approach on GH is to "tag" the current repo version, and GH treats this as 
a "release", making it very easy for users to navigate to.

**Comment by martinamorris** [comment]
for example, if you look at the ergm repo:

https://github.com/statnet/ergm

there's a tab up above called "releases" that lists 31 releases, click on 
that and you'll see all of them with tar and zip files...

https://github.com/statnet/ergm/releases

all this is automated as soon as you tag. (yay GitHub!!)

**Comment by martinamorris** [comment]
Tagged, see https://github.com/statnet/Workshops/releases
